version: "3.3"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "1323:1323"
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
