@url = https://localhost:5001

@user_token = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwidW5pcXVlX25hbWUiOiI0IiwianRpIjoiZDZkY2I5ODQtMDU4Mi00NTIwLTgxYzktOTk5NGNkZWU4MzUwIiwiaWF0IjoiMTYwODEwNjc4MSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCIsIm5iZiI6MTYwODEwNjc4MSwiZXhwIjoxNjA4MTA3MDgxLCJpc3MiOiJwbGFuZG9faXNzdWVyIn0.H5xRTkL1M6o7bdKIc7FhtWJftyy5e_HtrzRcwzu_x2I

@manager_token = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwidW5pcXVlX25hbWUiOiIyIiwianRpIjoiYTYwOGYwNTMtYzdlNC00YTUyLTg2NzEtNjBiYTdkNmNiYTI2IiwiaWF0IjoiMTYwODMxNzY4MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1hbmFnZXIiLCJuYmYiOjE2MDgzMTc2ODMsImV4cCI6MTYwODMxNzk4MywiaXNzIjoicGxhbmRvX2lzc3VlciJ9.sXXdrsEhrf7IH5Bk5xoM4X8wvY-7nMMDJmlnnIPutYs

### create order

POST {{url}}/order/create HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json

{
    "title": "Куртка SAMURAI",
    "laundryId": 1,
    "clientId": 4
}

### cancel order

POST {{url}}/order/cancel HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json

{
    "orderId": 2
}

### add service to order

POST {{url}}/order/service/add HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json

{
    "serviceId": 1,
    "orderId": 2
}

### remove service

POST {{url}}/order/service/remove HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json

{
    "orderId": 2,
    "serviceId": 2
}

### put order in progress

POST {{url}}/order/progress HTTP/1.1
Authorization: {{manager_token}}
Content-Type: application/json

{
    "orderId" : 2
}

### complete service

POST {{url}}/order/service/complete HTTP/1.1
Authorization: {{manager_token}}
Content-Type: application/json

{
    "orderId": 2,
    "serviceId": 1
}

### finish order

POST {{url}}/order/finish HTTP/1.1
Authorization: {{manager_token}}
Content-Type: application/json

{
    "orderId": 2
}

### pass order

POST {{url}}/order/pass HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json

{
    "orderId": 2
}

### get order

GET {{url}}/order/2 HTTP/1.1
Authorization: {{user_token}}
Content-Type: application/json
