# server configuration
server:
  host: "localhost"
  port: 8000

# database configuration
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "plandodb_test"
